FROM alpine:3.13

RUN apk add \
        bash \
        curl \
        file \
        gcc \
        gnupg \
        less \
        make \
        musl-dev \
        shadow \
        sudo \
        vim

RUN mkdir -p /build

ARG BUILDER_UID=1000
ARG BUILDER_GID=1000
ENV BUILDER_UID=$BUILDER_UID
ENV BUILDER_GID=$BUILDER_GID

COPY Dockerfiles/fix-id.sh /usr/local/sbin/fix-id.sh

ENTRYPOINT ["/usr/local/sbin/fix-id.sh"]
